### ISSUE TITLE
After the tajo service is installed in the Spack, the tajo service cannot be started.[tajo@0.11.3]

### ISSUE THREAD

**Issue by Tom-python0121** [tajo/tajo#5]
### Steps to reproduce the issue

```console
see:
root@ubuntu:tajo# ls
bin     logs                            tajo-catalog-common-0.11.3.jar  tajo-client-example-0.11.3.jar  tajo-metrics-0.11.3.jar     tajo-rpc-protobuf-0.11.3.jar    tajo-storage-hdfs-0.11.3.jar
conf    share                           tajo-catalog-server-0.11.3.jar  tajo-common-0.11.3.jar          tajo-plan-0.11.3.jar        tajo-sql-parser-0.11.3.jar      tajo-storage-jdbc-0.11.3.jar
extlib  tajo-algebra-0.11.3.jar         tajo-cli-0.11.3.jar             tajo-core-0.11.3.jar            tajo-pullserver-0.11.3.jar  tajo-storage-common-0.11.3.jar  tajo-storage-pgsql-0.11.3.jar
lib     tajo-catalog-client-0.11.3.jar  tajo-client-0.11.3.jar          tajo-hive-0.11.3.jar            tajo-rpc-common-0.11.3.jar  tajo-storage-hbase-0.11.3.jar   tajo-ws-rs-0.11.3.jar
root@ubuntu:tajo#vim conf/tajo-env.sh
root@ubuntu:bin#tajo version
Tajo 0.11.3
Git git@github.com:hyunsik/tajo.git -r 11740fd6797cb9457b4a35bfb37957b468d8ec7c
Compiled by hyunsik on 2016-05-10T21:45Z
Compiled with protoc 2.5.0
From source with checksum d1c9ebb6c4db3f7b6a830f550c5bf
This command was run using /home/linux-ubuntu18.04-aarch64/gcc-7.5.0/tajo-0.11.3-2yosy5if5tryxj5y2nka764xhdbw6fei/tajo-common-0.11.3.jar

root@ubuntu:bin#./start-tajo.sh
Starting single TajoMaster
starting master, logging to /home/linux-ubuntu18.04-aarch64/gcc-7.5.0/tajo-0.11.3-2yosy5if5tryxj5y2nka764xhdbw6fei/bin/../logs/tajo-root-master-ubuntu.out
root@localhost's password:
localhost: starting worker, logging to /home/linux-ubuntu18.04-aarch64/gcc-7.5.0/tajo-0.11.3-2yosy5if5tryxj5y2nka764xhdbw6fei/bin/../logs/tajo-root-worker-ubuntu.out
./start-tajo.sh: line 61: [: =: unary operator expected
./start-tajo.sh: line 62: [: =: unary operator expected
./start-tajo.sh: line 63: [: =: unary operator expected
./start-tajo.sh: line 67: [: =: unary operator expected
./start-tajo.sh: line 68: [: =: unary operator expected
./start-tajo.sh: line 69: [: =: unary operator expected
Tajo master web UI: http://:
Tajo Client Service: :
root@ubuntu:bin#jps
112655 Jps
root@ubuntu:bin#tsql
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
        at org.apache.hadoop.conf.Configuration.set(Configuration.java:1357)
        at org.apache.hadoop.conf.Configuration.set(Configuration.java:1338)
        at org.apache.tajo.conf.TajoConf.setVar(TajoConf.java:713)
        at org.apache.tajo.conf.TajoConf.setVar(TajoConf.java:725)
        at org.apache.tajo.cli.tsql.TajoCli.<init>(TajoCli.java:254)
        at org.apache.tajo.cli.tsql.TajoCli.main(TajoCli.java:719)
```
I don't know why it reports these Java errors, feel is the test source code problem, can you help me to analyze it?
### Information on your system
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-aarch64
* **Concretizer:** original

**Comment by Tom-python0121** [comment]
see:https://issues.apache.org/jira/browse/TAJO-2190
